name: dart2_js_interop_casts

environment:
  sdk: ">=2.0.0-dev.55.0 <3.0.0"

dev_dependencies:
  build_runner: ^0.8.9
  build_test: ^0.10.2+3
  build_web_compilers: 0.4.0+1
  js: ^0.6.1
  test: ^0.12.38
